name: Stage the app

on:
  pull_request:
    types: [labeled]

jobs:
  build:
    runs-on: ubuntu-latest

    if: contains(github.event.pull_request.labels.*.name, 'stage')

    steps:
      - name: Display staging message
        run: echo "Staging workflow triggered for PR labeled 'stage'"
